CREATE DATABASE IF NOT EXISTS PROJET_BOISSON ;
USE PROJET_BOISSON ;

CREATE TABLE Recette (
	idRecette INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	titre VARCHAR(100) NOT NULL,
	composition TEXT NOT NULL,
	preparation TEXT NOT NULL
) ;

CREATE TABLE Aliment (
	idAliment INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	nom VARCHAR(30) NOT NULL,
	supercategorie TEXT NOT NULL
) ;


CREATE TABLE Constitution(
	idConst INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	idAliment INT(6) UNSIGNED,
	idRecette INT(6) UNSIGNED,
	FOREIGN KEY(idAliment) REFERENCES Aliment ON DELETE CASCADE,
	FOREIGN KEY(idRecette) REFERENCES Recette ON DELETE CASCADE
) ;