DROP DATABASE IF EXISTS projet_boissons ;
CREATE DATABASE IF NOT EXISTS projet_boissons ;
USE projet_boissons ;

CREATE TABLE Recettes (
	idRecette INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	titre VARCHAR(100) NOT NULL UNIQUE,
	composition TEXT NOT NULL,
	preparation TEXT NOT NULL
) ;

CREATE TABLE Aliments (
	idAliment INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	nomAliment VARCHAR(30) NOT NULL UNIQUE
) ;

CREATE TABLE Supercategories (
	idSuperCat INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	idAliment INT(6) UNSIGNED,
	idAlimentSuperCategorie INT(6) UNSIGNED,
	FOREIGN KEY (idAliment) REFERENCES Aliments(idAliment) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (idAlimentSuperCategorie) REFERENCES Aliments(idAliment) ON UPDATE CASCADE ON DELETE CASCADE
) ;

CREATE TABLE Constitution (
	idConst INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	idRecette INT(6) UNSIGNED,
	idAliment INT(6) UNSIGNED,
	FOREIGN KEY (idAliment) REFERENCES Aliments(idAliment) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (idRecette) REFERENCES Recettes(idRecette) ON UPDATE CASCADE ON DELETE CASCADE
) ;

CREATE TABLE Utilisateurs (
	idUtilisateur INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	pseudo VARCHAR(30) NOT NULL UNIQUE,
	mdp VARCHAR(30) NOT NULL,
	sexe VARCHAR(1),
	prenom VARCHAR(30),
	nom VARCHAR(30),
	age INT(6) UNSIGNED,
	email VARCHAR(30),
	telephone VARCHAR(30),
	adresse VARCHAR(100),
	codePostal VARCHAR(30),
	ville VARCHAR(30),
	dateCreation DATETIME NOT NULL
) ;

CREATE TABLE RecettesPreferees (
	idRP INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	idUtilisateur INT(6) UNSIGNED NOT NULL,
	idRecette INT(6) UNSIGNED NOT NULL,
	FOREIGN KEY (idUtilisateur) REFERENCES Utilisateurs(idUtilisateur) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (idRecette) REFERENCES Recettes(idRecette) ON UPDATE CASCADE ON DELETE CASCADE
)